steps:
  # --- YENİ EKLENEN ADIM: BİRİM TESTLERİ ---
  # Docker imajı oluşturmadan önce kodu test ediyoruz.
  # Hata varsa süreç burada durur.
  - name: "python:3.11-slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt
        python -m unittest test_app.py
  # 1. Adım: Docker imajını oluştur
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/hello-run-repo/${_SERVICE_NAME}:${SHORT_SHA}"
      - "."

  # 2. Adım: İmajı Artifact Registry'ye yükle
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/hello-run-repo/${_SERVICE_NAME}:${SHORT_SHA}"

  # 3. Adım: Cloud Run'a deploy et (GÜNCELLENDİ)
  # Eski 'google-cloud-sdk' yerine güncel 'cloudsdktool' kullanıyoruz
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/hello-run-repo/${_SERVICE_NAME}:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--allow-unauthenticated"

# Oluşturulan imajlar
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/hello-run-repo/${_SERVICE_NAME}:${SHORT_SHA}"

# Değişkenler
substitutions:
  _SERVICE_NAME: "hello-servisim"
  _REGION: "europe-west1"

# Log ayarı
options:
  logging: CLOUD_LOGGING_ONLY
